import { BorealError } from "@boreal/core";
import type { ParsedArgs } from "./args.js";

export type FlagType = "boolean" | "value";

export interface FlagDefinition {
  readonly name: string;
  readonly type: FlagType;
  readonly summary: string;
  readonly repeatable?: boolean;
}

export interface CommandDefinition {
  readonly path: readonly string[];
  readonly category:
    | "workspace"
    | "work"
    | "dependency"
    | "evidence"
    | "source"
    | "claim"
    | "decision"
    | "context"
    | "search"
    | "reservation"
    | "agent"
    | "session"
    | "operation"
    | "workflow"
    | "install"
    | "export"
    | "import"
    | "vault"
    | "raw"
    | "wiki"
    | "duplicate"
    | "merge"
    | "compact"
    | "sync"
    | "ledger"
    | "snapshot"
    | "doctor"
    | "lock"
    | "meta";
  readonly summary: string;
  readonly usage: string;
  readonly description?: string;
  readonly flags: readonly FlagDefinition[];
  readonly positionals?: {
    readonly label: string;
    readonly min: number;
    readonly max?: number;
  };
  readonly requiresWorkspace: boolean;
  readonly supportsJson: boolean;
}

export type CommandLockRequirement = "none" | "state" | "index" | "state+index" | "recovery";
export type HumanOutputKind = "table" | "record" | "markdown" | "none";

export interface CommandBehaviorMetadata {
  readonly readOnly: boolean;
  readonly destructive: boolean;
  readonly writesState: boolean;
  readonly writesGeneratedArtifacts: boolean;
  readonly requiresFreshIndex: boolean;
  readonly concurrencySafe: boolean;
  readonly requiresLock: CommandLockRequirement;
  readonly supportsExplain: boolean;
  readonly maxResultSizeChars: number;
  readonly jsonOutputSchema: string;
  readonly humanOutputKind: HumanOutputKind;
  readonly examples: readonly string[];
}

export const GLOBAL_FLAGS: readonly FlagDefinition[] = [
  {
    name: "workspace",
    type: "value",
    summary: "Workspace directory. Defaults to the current directory.",
  },
  {
    name: "json",
    type: "boolean",
    summary: "Emit a JSON envelope instead of human-readable text.",
  },
  {
    name: "actor",
    type: "value",
    summary: "Actor identifier to record in command events.",
  },
  {
    name: "actor-kind",
    type: "value",
    summary: "Actor kind to record in command events.",
  },
  {
    name: "session",
    type: "value",
    summary: "Session identifier to group local command operations.",
  },
  {
    name: "help",
    type: "boolean",
    summary: "Show command help.",
  },
];

const flag = (
  name: string,
  type: FlagType,
  summary: string,
  repeatable = false,
): FlagDefinition => ({
  name,
  type,
  summary,
  repeatable,
});

const commandMetadata = (
  command: string,
  input: Omit<CommandBehaviorMetadata, "supportsExplain" | "jsonOutputSchema" | "examples"> &
    Partial<Pick<CommandBehaviorMetadata, "supportsExplain" | "jsonOutputSchema">> & {
      readonly examples: readonly string[];
    },
): CommandBehaviorMetadata => ({
  supportsExplain: false,
  jsonOutputSchema: `boreal.cli.${command.replace(/\s+/gu, ".")}.v1`,
  ...input,
});

export const COMMAND_DEFINITIONS: readonly CommandDefinition[] = [
  {
    path: ["init"],
    category: "workspace",
    summary: "Initialize a Boreal workspace.",
    usage:
      "bwrk init [--workspace <dir>|--project-root <dir>] [--setup-memory] [--memory-root <dir>] [--memory-layout in-repo|child|sibling] [--separate-git] [--install-root <dir>] [--skill-target codex|claude...] [--folder-scoped] [--interactive] [--json]",
    description:
      "Creates the workspace metadata directory and state store. With setup flags, also writes .boreal/project.json and scaffolds the selected memory root.",
    flags: [
      flag("project-root", "value", "Project root alias for --workspace during setup."),
      flag("setup-memory", "boolean", "Write project setup config and scaffold the selected memory root."),
      flag("memory-root", "value", "Memory root path. Relative paths resolve from the project root. Defaults to memory."),
      flag("memory-layout", "value", "Memory layout: in-repo, child, or sibling. Defaults to in-repo."),
      flag("separate-git", "boolean", "Record memory as a separate Git boundary in project setup config."),
      flag("install-root", "value", "Skill install root. Relative paths resolve from the project root. Defaults to .agents/skills."),
      flag("skill-target", "value", "Skill target to record: codex or claude. Repeatable.", true),
      flag("folder-scoped", "boolean", "Record skills as folder-scoped for sessions opened inside the install folder."),
      flag("interactive", "boolean", "Prompt for project setup fields in a TTY.")
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["commands"],
    category: "meta",
    summary: "List the registered command surface.",
    usage: "bwrk commands [--format table|markdown] [--json]",
    description: "Prints the command registry used by validation, help, documentation generation, and machine consumers.",
    flags: [flag("format", "value", "Human output format: table or markdown.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["workflows", "list"],
    category: "workflow",
    summary: "List checked-in workflow playbooks.",
    usage: "bwrk workflows list [--json]",
    description: "Lists Boreal v1 workflow playbooks from the checked-in workflows directory.",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["workflows", "show"],
    category: "workflow",
    summary: "Show a workflow playbook.",
    usage: "bwrk workflows show <workflow-id|path|slug> [--json]",
    description: "Shows one checked-in workflow by ID, relative path, or slug.",
    flags: [],
    positionals: { label: "workflow reference", min: 1, max: 1 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["install", "codex"],
    category: "install",
    summary: "Install Boreal skills for Codex.",
    usage: "bwrk install codex [--install-root <dir>] [--dry-run] [--json]",
    description: "Installs project-scoped Boreal skill adapters for Codex. Defaults to .agents and writes .agents/skills/boreal-*.",
    flags: [
      flag("install-root", "value", "Skill install root. Defaults to .agents under the selected workspace."),
      flag("dry-run", "boolean", "Plan install paths without writing files.")
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["install", "claude"],
    category: "install",
    summary: "Install Boreal skills for Claude.",
    usage: "bwrk install claude [--install-root <dir>] [--dry-run] [--json]",
    description: "Installs project-scoped Boreal skill adapters for Claude. Defaults to .claude and writes .claude/skills/boreal-*.",
    flags: [
      flag("install-root", "value", "Skill install root. Defaults to .claude under the selected workspace."),
      flag("dry-run", "boolean", "Plan install paths without writing files.")
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["install", "skills"],
    category: "install",
    summary: "Install Boreal generic skill files.",
    usage: "bwrk install skills [--install-root <dir>] [--dry-run] [--json]",
    description: "Installs namespaced Boreal skill source folders into a folder-scoped skill root. Defaults to .agents/skills.",
    flags: [
      flag("install-root", "value", "Skill install root. Defaults to .agents/skills under the selected workspace."),
      flag("dry-run", "boolean", "Plan install paths without writing files.")
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["prime"],
    category: "agent",
    summary: "Show the compact agent/session startup brief.",
    usage: "bwrk prime [--agent <agent-id>] [--label <label>...] [--json]",
    description:
      "Summarizes workspace sync health, agent coordination state, current session operations, and the next concrete protocol commands.",
    flags: [
      flag("agent", "value", "Agent identifier. Defaults to the CLI actor."),
      flag("label", "value", "Only consider ready work with this label when computing claimable work.", true),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "create"],
    category: "work",
    summary: "Create a work item.",
    usage:
      "bwrk work create <title> [--description <text>] [--priority low|normal|high|critical] [--kind <kind>] [--label <label>...] [--acceptance <text>...] [--ready] [--json]",
    flags: [
      flag("description", "value", "Work description."),
      flag("priority", "value", "Work priority: low, normal, high, or critical."),
      flag("kind", "value", "Work kind."),
      flag("label", "value", "Label to attach to the work item.", true),
      flag("acceptance", "value", "Acceptance criterion.", true),
      flag("ready", "boolean", "Create the item as ready when policy allows it."),
    ],
    positionals: { label: "title", min: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "ready"],
    category: "work",
    summary: "Mark work ready.",
    usage: "bwrk work ready <work-id> [--json]",
    flags: [],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "list"],
    category: "work",
    summary: "List work items.",
    usage: "bwrk work list [--ready] [--status <status>] [--label <label>...] [--limit <n>] [--json]",
    flags: [
      flag("ready", "boolean", "Only include ready work."),
      flag("status", "value", "Only include work with this status."),
      flag("label", "value", "Only include work with this label.", true),
      flag("limit", "value", "Maximum number of work items to print. Defaults to 100, max 1000."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "next"],
    category: "work",
    summary: "Show the next ready work.",
    usage: "bwrk work next [--label <label>...] [--limit <n>] [--json]",
    description: "Lists claimable ready work from the live runtime view, ordered by priority and title.",
    flags: [
      flag("label", "value", "Only include work with this label.", true),
      flag("limit", "value", "Maximum number of ready work items to print. Defaults to 10, max 1000."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "show"],
    category: "work",
    summary: "Show one work item.",
    usage: "bwrk work show <work-id> [--json]",
    flags: [],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "block"],
    category: "work",
    summary: "Make one work item depend on another.",
    usage: "bwrk work block <work-id> <blocked-by-work-id> [--json]",
    flags: [],
    positionals: { label: "work ids", min: 2, max: 2 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["dep", "add"],
    category: "dependency",
    summary: "Add a work dependency edge.",
    usage: "bwrk dep add <work-id> <depends-on-work-id> [--type blocks] [--json]",
    description: "Adds a canonical block dependency between work items. This is the dependency-focused alias for `work block`.",
    flags: [flag("type", "value", "Dependency edge type. Currently only blocks is supported.")],
    positionals: { label: "work ids", min: 2, max: 2 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["dep", "remove"],
    category: "dependency",
    summary: "Remove a work dependency edge.",
    usage: "bwrk dep remove <work-id> <depends-on-work-id> [--type blocks] [--json]",
    description: "Removes a canonical block dependency edge and restores the dependent work to derived readiness.",
    flags: [flag("type", "value", "Dependency edge type. Currently only blocks is supported.")],
    positionals: { label: "work ids", min: 2, max: 2 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["dep", "tree"],
    category: "dependency",
    summary: "Show the dependency tree for work.",
    usage: "bwrk dep tree <work-id> [--json]",
    description: "Reads canonical block graph edges and returns the recursive blockers for one work item.",
    flags: [],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["dep", "cycles"],
    category: "dependency",
    summary: "List dependency cycles.",
    usage: "bwrk dep cycles [--json]",
    description: "Lists cycles in canonical block graph edges.",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "reserve"],
    category: "work",
    summary: "Reserve ready work for an agent.",
    usage:
      "bwrk work reserve <work-id> --agent <agent-id> [--purpose <text>] [--expires-at <iso>|--ttl <duration>] [--force --reason <text>] [--json]",
    flags: [
      flag("agent", "value", "Agent identifier taking the reservation."),
      flag("purpose", "value", "Reservation purpose."),
      flag("expires-at", "value", "ISO timestamp when the reservation should expire."),
      flag("ttl", "value", "Relative reservation duration, for example 30m, 2h, or 1d."),
      flag("force", "boolean", "Allow a documented reservation of non-ready work."),
      flag("reason", "value", "Required reason when --force is set."),
    ],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "claim"],
    category: "work",
    summary: "Atomically claim next ready work.",
    usage:
      "bwrk work claim [--label <label>...] [--agent <agent-id>] [--purpose <text>] [--expires-at <iso>|--ttl <duration>] [--query <text>] [--limit <n>] [--json]",
    description:
      "Finds the next live ready work item, reserves it in one runtime write, refreshes context/search projections, and returns a handoff bundle.",
    flags: [
      flag("label", "value", "Only claim work with this label.", true),
      flag("agent", "value", "Agent identifier taking the reservation. Defaults to the CLI actor."),
      flag("purpose", "value", "Reservation purpose."),
      flag("expires-at", "value", "ISO timestamp when the reservation should expire."),
      flag("ttl", "value", "Relative reservation duration, for example 30m, 2h, or 1d."),
      flag("query", "value", "Optional handoff search query. Defaults to the claimed work context."),
      flag("limit", "value", "Maximum number of handoff search results. Defaults to 8, max 50."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "release"],
    category: "work",
    summary: "Release a work reservation.",
    usage: "bwrk work release <work-id> [--json]",
    description: "Marks the active reservation released and restores the work item to derived readiness.",
    flags: [],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "renew"],
    category: "work",
    summary: "Renew a work reservation.",
    usage: "bwrk work renew <work-id> (--expires-at <iso>|--ttl <duration>) [--json]",
    description: "Extends the active reservation for a work item.",
    flags: [
      flag("expires-at", "value", "ISO timestamp when the reservation should expire."),
      flag("ttl", "value", "Relative reservation duration, for example 30m, 2h, or 1d."),
    ],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "verify"],
    category: "work",
    summary: "Verify work with evidence.",
    usage: "bwrk work verify <work-id> --evidence <evidence-id>... [--verdict passed|failed] [--notes <text>] [--json]",
    flags: [
      flag("evidence", "value", "Evidence record to attach to the verification.", true),
      flag("verdict", "value", "Verification verdict. Defaults to passed."),
      flag("notes", "value", "Verification notes."),
    ],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["work", "close"],
    category: "work",
    summary: "Close verified work.",
    usage: "bwrk work close <work-id> [--reason <text>] [--json]",
    flags: [flag("reason", "value", "Close reason.")],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["evidence", "add"],
    category: "evidence",
    summary: "Add an evidence record.",
    usage:
      "bwrk evidence add <work-id> --summary <text> [--kind <kind>] [--outcome passed|failed|observed|unknown] [--command <cmd>] [--uri <uri>] [--json]",
    flags: [
      flag("summary", "value", "Evidence summary."),
      flag("kind", "value", "Evidence kind."),
      flag("outcome", "value", "Evidence outcome. Defaults to observed."),
      flag("command", "value", "Command that produced the evidence."),
      flag("uri", "value", "URI for external evidence."),
    ],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["source", "add"],
    category: "source",
    summary: "Add a knowledge source.",
    usage:
      "bwrk source add --title <text> --uri <uri> [--kind raw|document|chat|code|artifact] [--summary <text>] [--json]",
    flags: [
      flag("title", "value", "Source title."),
      flag("uri", "value", "Source URI."),
      flag("kind", "value", "Source kind. Defaults to document."),
      flag("summary", "value", "Source summary."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["source", "list"],
    category: "source",
    summary: "List knowledge sources.",
    usage: "bwrk source list [--kind raw|document|chat|code|artifact] [--limit <n>] [--json]",
    flags: [
      flag("kind", "value", "Only include sources with this kind."),
      flag("limit", "value", "Maximum number of sources to print. Defaults to 100, max 1000."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["source", "show"],
    category: "source",
    summary: "Show one knowledge source.",
    usage: "bwrk source show <source-id> [--json]",
    flags: [],
    positionals: { label: "source id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["claim", "create"],
    category: "claim",
    summary: "Create a knowledge claim.",
    usage:
      "bwrk claim create --statement <text> [--status proposed|accepted|rejected|stale] [--source <source-id>...] [--evidence <evidence-id>...] [--json]",
    flags: [
      flag("statement", "value", "Claim statement."),
      flag("status", "value", "Claim status. Defaults to proposed."),
      flag("source", "value", "Source supporting the claim.", true),
      flag("evidence", "value", "Evidence supporting the claim.", true),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["claim", "list"],
    category: "claim",
    summary: "List knowledge claims.",
    usage: "bwrk claim list [--status proposed|accepted|rejected|stale] [--source <source-id>] [--limit <n>] [--json]",
    flags: [
      flag("status", "value", "Only include claims with this status."),
      flag("source", "value", "Only include claims referencing this source."),
      flag("limit", "value", "Maximum number of claims to print. Defaults to 100, max 1000."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["claim", "show"],
    category: "claim",
    summary: "Show one knowledge claim.",
    usage: "bwrk claim show <claim-id> [--json]",
    flags: [],
    positionals: { label: "claim id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["decision", "create"],
    category: "decision",
    summary: "Create a decision record.",
    usage:
      "bwrk decision create --title <text> --decision <text> [--context <text>] [--status proposed|accepted|superseded|rejected] [--consequence <text>...] [--source <source-id>...] [--json]",
    flags: [
      flag("title", "value", "Decision title."),
      flag("decision", "value", "Decision text."),
      flag("context", "value", "Decision context."),
      flag("status", "value", "Decision status. Defaults to accepted."),
      flag("consequence", "value", "Decision consequence.", true),
      flag("source", "value", "Source informing the decision.", true),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["decision", "list"],
    category: "decision",
    summary: "List decisions.",
    usage: "bwrk decision list [--status proposed|accepted|superseded|rejected] [--source <source-id>] [--limit <n>] [--json]",
    flags: [
      flag("status", "value", "Only include decisions with this status."),
      flag("source", "value", "Only include decisions referencing this source."),
      flag("limit", "value", "Maximum number of decisions to print. Defaults to 100, max 1000."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["decision", "show"],
    category: "decision",
    summary: "Show one decision.",
    usage: "bwrk decision show <decision-id> [--json]",
    flags: [],
    positionals: { label: "decision id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["context", "rebuild"],
    category: "context",
    summary: "Rebuild context pack projections.",
    usage: "bwrk context rebuild [--json]",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["context", "show"],
    category: "context",
    summary: "Show a work context pack.",
    usage: "bwrk context show <work-id> [--json]",
    flags: [],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["context", "search"],
    category: "context",
    summary: "Search context packs.",
    usage: "bwrk context search <query> [--limit <n>] [--explain] [--json]",
    description: "Searches the fresh local search index but only returns context pack and bounded context chunk documents.",
    flags: [
      flag("limit", "value", "Maximum number of context results to print. Max 100."),
      flag("explain", "boolean", "Include query tokens, score breakdown, and field-level matches in JSON output."),
    ],
    positionals: { label: "query", min: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["search", "index"],
    category: "search",
    summary: "Build the local search index.",
    usage: "bwrk search index [--json]",
    description: "Writes a content-hashed index to .boreal/runtime/search-index.json.",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["search", "query"],
    category: "search",
    summary: "Search work and knowledge records.",
    usage: "bwrk search query <query> [--limit <n>] [--explain] [--json]",
    description:
      "Searches work, evidence, sources, claims, decisions, context packs, and bounded context chunks using a fresh hybrid local index.",
    flags: [
      flag("limit", "value", "Maximum number of search results to print. Max 100."),
      flag("explain", "boolean", "Include query tokens, score breakdown, and field-level matches in JSON output."),
    ],
    positionals: { label: "query", min: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["reservation", "list"],
    category: "reservation",
    summary: "List reservations.",
    usage:
      "bwrk reservation list [--agent <agent-id>] [--work <work-id>] [--status active|released|expired|all] [--expired] [--limit <n>] [--json]",
    description: "Shows reservation ownership and expiration state for multi-agent coordination.",
    flags: [
      flag("agent", "value", "Only include reservations for this agent."),
      flag("work", "value", "Only include reservations for this work item."),
      flag("status", "value", "Only include reservations with this status. Defaults to active."),
      flag("expired", "boolean", "Only include reservations whose expiration timestamp is in the past."),
      flag("limit", "value", "Maximum number of reservations to print. Defaults to 100, max 1000."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["agent", "finish"],
    category: "agent",
    summary: "Finish work with an active reservation using evidence and verification.",
    usage:
      "bwrk agent finish <work-id> --summary <text> (--close --reason <text>|--release) [--agent <agent-id>] [--kind command|test|diff|review|artifact|note] [--outcome passed|failed|observed|unknown] [--command <cmd>] [--uri <uri>] [--verdict passed|failed] [--notes <text>] [--json]",
    description:
      "Requires the requested agent to own the active reservation, records evidence, verifies the work, and closes or releases the reservation.",
    flags: [
      flag("summary", "value", "Evidence summary."),
      flag("agent", "value", "Agent identifier. Defaults to the CLI actor."),
      flag("kind", "value", "Evidence kind. Defaults to command."),
      flag("outcome", "value", "Evidence outcome. Defaults to the verification verdict outcome."),
      flag("command", "value", "Command that produced the evidence."),
      flag("uri", "value", "Evidence artifact URI."),
      flag("verdict", "value", "Verification verdict. Defaults to passed."),
      flag("notes", "value", "Verification notes."),
      flag("close", "boolean", "Close the work after passing verification and release its reservation."),
      flag("reason", "value", "Close reason. Required with --close."),
      flag("release", "boolean", "Release the reservation after verification without closing."),
    ],
    positionals: { label: "work id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["agent", "start"],
    category: "agent",
    summary: "Start or resume safe agent work.",
    usage:
      "bwrk agent start [--agent <agent-id>] [--label <label>...] [--purpose <text>] [--expires-at <iso>|--ttl <duration>] [--query <text>] [--limit <n>] [--json]",
    description:
      "Preflights reservation state, blocks on stale active reservations, resumes existing active work, or atomically claims ready work and returns a handoff bundle.",
    flags: [
      flag("agent", "value", "Agent identifier. Defaults to the CLI actor."),
      flag("label", "value", "Only claim ready work with this label.", true),
      flag("purpose", "value", "Reservation purpose when claiming work."),
      flag("expires-at", "value", "ISO timestamp when a new reservation should expire."),
      flag("ttl", "value", "Relative reservation duration for a new claim, for example 30m, 2h, or 1d."),
      flag("query", "value", "Optional handoff search query. Defaults to the selected work context."),
      flag("limit", "value", "Maximum number of handoff search results. Defaults to 8, max 50."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["agent", "guide"],
    category: "agent",
    summary: "Print the recommended agent work loop.",
    usage: "bwrk agent guide [--agent <agent-id>] [--label <label>...] [--json]",
    description:
      "Prints the compact command loop for starting work, recording evidence, verifying, renewing or releasing reservations, and doctor recovery.",
    flags: [
      flag("agent", "value", "Agent identifier. Defaults to the CLI actor."),
      flag("label", "value", "Label filter to include in start and status commands.", true),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["agent", "status"],
    category: "agent",
    summary: "Show agent coordination status.",
    usage: "bwrk agent status [--agent <agent-id>] [--label <label>...] [--json]",
    description:
      "Summarizes an agent's active and expired reservations, claim capacity, claimable ready work, and recommended next action.",
    flags: [
      flag("agent", "value", "Agent identifier. Defaults to the CLI actor."),
      flag("label", "value", "Only consider ready work with this label when computing claimable work.", true),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["session", "start"],
    category: "session",
    summary: "Start an agent protocol session.",
    usage: "bwrk session start [--id <session-id>] [--agent <agent-id>] [--label <label>...] [--json]",
    description:
      "Creates or echoes the normalized session ID used for local operation history, then returns the same startup brief as `prime`.",
    flags: [
      flag("id", "value", "Session identifier. Defaults to --session, BOREAL_SESSION_ID, or a generated ID."),
      flag("agent", "value", "Agent identifier. Defaults to the CLI actor."),
      flag("label", "value", "Only consider ready work with this label when computing claimable work.", true),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["session", "end"],
    category: "session",
    summary: "Summarize and close an agent protocol session.",
    usage: "bwrk session end [--id <session-id>] [--agent <agent-id>] [--label <label>...] [--json]",
    description:
      "Summarizes operation history, sync health, and active reservation state for the target session without deleting records.",
    flags: [
      flag("id", "value", "Session identifier. Defaults to --session, BOREAL_SESSION_ID, or local."),
      flag("agent", "value", "Agent identifier. Defaults to the CLI actor."),
      flag("label", "value", "Only consider ready work with this label when computing claimable work.", true),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["operation", "list"],
    category: "operation",
    summary: "List local command operations.",
    usage:
      "bwrk operation list [--session-id <id>] [--command <path>] [--status succeeded|failed|all] [--limit <n>] [--json]",
    description: "Shows local CLI operation audit records newest first.",
    flags: [
      flag("session-id", "value", "Only include operations from this session ID."),
      flag("command", "value", "Only include operations for this command path, for example 'work create'."),
      flag("status", "value", "Only include operations with this status. Defaults to all."),
      flag("limit", "value", "Maximum number of operations to print. Defaults to 50, max 1000."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["operation", "show"],
    category: "operation",
    summary: "Show one local command operation.",
    usage: "bwrk operation show <operation-id-or-prefix> [--json]",
    description: "Shows the full local operation record, including redacted argv and generated event IDs.",
    flags: [],
    positionals: { label: "operation id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["operation", "prune"],
    category: "operation",
    summary: "Prune local command operation records.",
    usage: "bwrk operation prune (--keep <n>|--before <iso>) [--json]",
    description: "Bounds local operation history without changing exported project records.",
    flags: [
      flag("keep", "value", "Keep the newest N operations, including this prune command's operation record."),
      flag("before", "value", "Delete operations finished before this ISO timestamp."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["operation", "repair"],
    category: "operation",
    summary: "Repair local operation-event causality links.",
    usage: "bwrk operation repair [--dry-run] [--json]",
    description:
      "Backfills unambiguous legacy event links and marks unlinked local operation history as legacy.",
    flags: [flag("dry-run", "boolean", "Report repair actions without writing them.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["export", "json"],
    category: "export",
    summary: "Export a stable JSON snapshot.",
    usage: "bwrk export json [--out <path>] [--json]",
    flags: [flag("out", "value", "Path to write. Defaults to stdout.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["export", "markdown"],
    category: "export",
    summary: "Export records as Markdown files.",
    usage: "bwrk export markdown [--out <dir>] [--json]",
    flags: [flag("out", "value", "Directory to write. Defaults to .boreal/exports/markdown.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["export", "ledgers"],
    category: "export",
    summary: "Export Git-friendly JSONL ledger files.",
    usage: "bwrk export ledgers [--out <dir>] [--json]",
    description: "Writes one JSONL file per runtime section, a tombstone ledger, and a manifest with content hashes.",
    flags: [flag("out", "value", "Directory to write. Defaults to .boreal/ledgers.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["import", "json"],
    category: "import",
    summary: "Import a JSON snapshot.",
    usage: "bwrk import json --from <path> [--allow-external-read] [--json]",
    flags: [
      flag("from", "value", "JSON export or file-store state document to import."),
      flag("allow-external-read", "boolean", "Allow importing a file outside the workspace."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["import", "ledgers"],
    category: "import",
    summary: "Import JSONL ledger files.",
    usage: "bwrk import ledgers --from <dir> [--allow-external-read] [--json]",
    description:
      "Reads a boreal.ledgers.v1 manifest, section JSONL files, and tombstones, validates hashes and references, then merges records.",
    flags: [
      flag("from", "value", "Ledger directory containing manifest.json to import."),
      flag("allow-external-read", "boolean", "Allow importing a ledger directory outside the workspace."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["vault", "init"],
    category: "vault",
    summary: "Initialize the configured memory vault.",
    usage: "bwrk vault init [--json]",
    description:
      "Creates the configured memory vault directories, Markdown indexes, and JSONL placeholders for durable Boreal project memory.",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["vault", "status"],
    category: "vault",
    summary: "Inspect the configured memory vault.",
    usage: "bwrk vault status [--json]",
    description: "Checks whether the configured memory vault scaffold is present and structurally valid.",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["raw", "add"],
    category: "raw",
    summary: "Append a raw source record to the memory vault.",
    usage: "bwrk raw add --title <text> [--uri <uri>] [--kind raw|document|chat|code|artifact] [--summary <text>] [--tag <tag>...] [--json]",
    description: "Adds an immutable source record to the configured memory vault raw index.",
    flags: [
      flag("title", "value", "Raw source title."),
      flag("uri", "value", "Source URI or local artifact reference."),
      flag("kind", "value", "Raw source kind. Defaults to raw."),
      flag("summary", "value", "Source summary."),
      flag("tag", "value", "Tag to attach to the source.", true)
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["wiki", "create"],
    category: "wiki",
    summary: "Create a memory vault wiki page.",
    usage: "bwrk wiki create <title> [--slug <slug>] [--summary <text>] [--source <raw-id>...] [--tag <tag>...] [--json]",
    description: "Creates a Markdown page under the configured memory vault wiki directory with Boreal frontmatter.",
    flags: [
      flag("slug", "value", "Page slug. Defaults to a normalized title slug."),
      flag("summary", "value", "Initial page summary."),
      flag("source", "value", "Raw source ID backing the page.", true),
      flag("tag", "value", "Tag to attach to the page.", true)
    ],
    positionals: { label: "title", min: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["duplicate", "scan"],
    category: "duplicate",
    summary: "Scan work and vault records for likely duplicates.",
    usage: "bwrk duplicate scan [--domain all|work|raw|wiki] [--json]",
    description: "Finds duplicate candidates and emits non-destructive manual merge plans.",
    flags: [flag("domain", "value", "Domain to scan. Defaults to all.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["merge", "plan"],
    category: "merge",
    summary: "Print a non-destructive merge review plan.",
    usage: "bwrk merge plan --domain work|raw|wiki --survivor <id> --duplicate <id>... [--json]",
    description: "Builds a merge plan document for review. It does not mutate runtime state or vault files.",
    flags: [
      flag("domain", "value", "Domain being merged."),
      flag("survivor", "value", "Record ID to keep."),
      flag("duplicate", "value", "Duplicate record ID to review for merging.", true)
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["merge", "apply"],
    category: "merge",
    summary: "Apply a reviewed merge plan with source-preserving guards.",
    usage:
      "bwrk merge apply --domain work|raw|wiki --survivor <id> --duplicate <id>... --plan <plan-id> --confirm [--json]",
    description:
      "Applies a reviewed merge plan only when the exact plan ID and --confirm are supplied. Work duplicates are archived, and vault merges retain source records while recording the merge relation.",
    flags: [
      flag("domain", "value", "Domain being merged."),
      flag("survivor", "value", "Record ID to keep."),
      flag("duplicate", "value", "Duplicate record ID to merge.", true),
      flag("plan", "value", "Exact plan ID produced by merge plan or duplicate scan."),
      flag("confirm", "boolean", "Required confirmation gate for applying the merge.")
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["compact", "analyze"],
    category: "compact",
    summary: "Analyze compaction candidates without mutating records.",
    usage: "bwrk compact analyze [--domain all|work|wiki] [--older-than-days <n>] [--json]",
    description:
      "Finds old closed work and vault page compaction candidates, then emits review-only plans with preservation guarantees.",
    flags: [
      flag("domain", "value", "Domain to analyze. Defaults to all."),
      flag("older-than-days", "value", "Closed-work age threshold. Defaults to 30.")
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["compact", "apply"],
    category: "compact",
    summary: "Apply a reviewed compaction plan with archive preservation.",
    usage:
      "bwrk compact apply --domain work|wiki --target <id> --plan <plan-id> --summary <text> --confirm [--older-than-days <n>] [--json]",
    description:
      "Applies one compaction plan only when the target is still eligible and the exact plan ID plus --confirm are supplied. Original content is archived before the target is summarized.",
    flags: [
      flag("domain", "value", "Domain being compacted. Must be work or wiki."),
      flag("target", "value", "Target record or page ID from the compaction plan."),
      flag("plan", "value", "Exact plan ID produced by compact analyze."),
      flag("summary", "value", "Reviewed summary to keep on the compacted target."),
      flag("confirm", "boolean", "Required confirmation gate for applying compaction."),
      flag("older-than-days", "value", "Closed-work age threshold used to recompute the plan. Defaults to 30.")
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["sync", "status"],
    category: "sync",
    summary: "Show collaboration sync health.",
    usage: "bwrk sync status [--json]",
    description:
      "Checks whether Git-friendly ledgers and generated local search cache are present, parseable, and current.",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["ledger", "status"],
    category: "ledger",
    summary: "Compare exported JSONL ledgers with current runtime state.",
    usage: "bwrk ledger status [--dir <dir>] [--json]",
    description: "Checks whether a boreal.ledgers.v1 manifest and tombstone ledger are present, parseable, hash-valid, and current.",
    flags: [flag("dir", "value", "Ledger directory to inspect. Defaults to .boreal/ledgers.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["ledger", "delete"],
    category: "ledger",
    summary: "Delete a supported record and write a tombstone.",
    usage:
      "bwrk ledger delete <work|evidence|verification|source|claim|decision|graph-edge|reservation|projection|context-pack> <id> [--reason <text>] [--json]",
    description:
      "Deletes a supported unreferenced record from runtime state, records a tombstone in deletions.jsonl, and refreshes JSONL ledgers.",
    flags: [flag("reason", "value", "Optional deletion reason stored in the tombstone.")],
    positionals: { label: "record kind and id", min: 2, max: 2 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["snapshot", "create"],
    category: "snapshot",
    summary: "Create a recovery snapshot.",
    usage: "bwrk snapshot create [--name <slug>] [--json]",
    flags: [flag("name", "value", "Optional snapshot name slug.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["snapshot", "list"],
    category: "snapshot",
    summary: "List recovery snapshots.",
    usage: "bwrk snapshot list [--json]",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["snapshot", "show"],
    category: "snapshot",
    summary: "Show one recovery snapshot.",
    usage: "bwrk snapshot show <snapshot-id> [--json]",
    flags: [],
    positionals: { label: "snapshot id", min: 1, max: 1 },
    requiresWorkspace: true,
    supportsJson: true,
  },
  {
    path: ["doctor"],
    category: "doctor",
    summary: "Inspect workspace integrity.",
    usage: "bwrk doctor [--fix] [--strict] [--json]",
    description: "Checks state shape, references, graph consistency, reservations, verification policy, and stale readiness.",
    flags: [
      flag("fix", "boolean", "Apply supported safe repairs."),
      flag("strict", "boolean", "Treat warnings as a failing doctor result."),
    ],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["doctor", "skills"],
    category: "doctor",
    summary: "Inspect workflow, template, and skill integrity.",
    usage: "bwrk doctor skills [--json]",
    description: "Validates workflow command references, template references, skill workflow references, and duplicate workflow IDs.",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["lock", "inspect"],
    category: "lock",
    summary: "Inspect the workspace lock.",
    usage: "bwrk lock inspect [--json]",
    flags: [],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
  {
    path: ["lock", "break"],
    category: "lock",
    summary: "Break a stale or orphaned workspace lock.",
    usage: "bwrk lock break [--stale-only] [--json]",
    flags: [flag("stale-only", "boolean", "Only break locks older than the stale threshold.")],
    positionals: { label: "arguments", min: 0, max: 0 },
    requiresWorkspace: false,
    supportsJson: true,
  },
];

const COMMAND_BEHAVIOR: Readonly<Record<string, CommandBehaviorMetadata>> = {
  init: commandMetadata("init", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 20_000,
    humanOutputKind: "record",
    examples: [
      "bwrk init --json",
      "bwrk init --setup-memory --memory-root memory --install-root .agents/skills --skill-target codex --folder-scoped --json",
    ],
  }),
  commands: commandMetadata("commands", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 250_000,
    humanOutputKind: "table",
    examples: ["bwrk commands --json", "bwrk commands --format markdown"],
  }),
  "workflows list": commandMetadata("workflows list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 250_000,
    humanOutputKind: "table",
    examples: ["bwrk workflows list --json"],
  }),
  "workflows show": commandMetadata("workflows show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 250_000,
    humanOutputKind: "markdown",
    examples: ["bwrk workflows show boreal.workflow.launch-sprint.v1"],
  }),
  "install codex": commandMetadata("install codex", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 250_000,
    humanOutputKind: "record",
    examples: ["bwrk install codex --dry-run --json"],
  }),
  "install claude": commandMetadata("install claude", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 250_000,
    humanOutputKind: "record",
    examples: ["bwrk install claude --dry-run --json"],
  }),
  "install skills": commandMetadata("install skills", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 250_000,
    humanOutputKind: "record",
    examples: ["bwrk install skills --dry-run --json"],
  }),
  prime: commandMetadata("prime", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 125_000,
    humanOutputKind: "record",
    examples: ["bwrk prime --agent agent-a --label hardening --json"],
  }),
  "work create": commandMetadata("work create", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work create 'Audit locks' --label hardening --ready --json"],
  }),
  "work ready": commandMetadata("work ready", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work ready bw_work_example --json"],
  }),
  "work list": commandMetadata("work list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 25_000,
    humanOutputKind: "table",
    examples: ["bwrk work list --status ready --limit 10 --json"],
  }),
  "work next": commandMetadata("work next", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 75_000,
    humanOutputKind: "table",
    examples: ["bwrk work next --label hardening --json"],
  }),
  "work show": commandMetadata("work show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work show bw_work_example --json"],
  }),
  "work block": commandMetadata("work block", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work block bw_work_blocked bw_work_blocker --json"],
  }),
  "dep add": commandMetadata("dep add", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk dep add bw_work_blocked bw_work_blocker --json"],
  }),
  "dep remove": commandMetadata("dep remove", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk dep remove bw_work_blocked bw_work_blocker --json"],
  }),
  "dep tree": commandMetadata("dep tree", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "table",
    examples: ["bwrk dep tree bw_work_example --json"],
  }),
  "dep cycles": commandMetadata("dep cycles", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "table",
    examples: ["bwrk dep cycles --json"],
  }),
  "work reserve": commandMetadata("work reserve", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work reserve bw_work_example --agent agent-a --ttl 2h --json"],
  }),
  "work claim": commandMetadata("work claim", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state+index",
    maxResultSizeChars: 150_000,
    humanOutputKind: "record",
    examples: ["bwrk work claim --agent agent-a --label hardening --json"],
  }),
  "work release": commandMetadata("work release", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work release bw_work_example --json"],
  }),
  "work renew": commandMetadata("work renew", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work renew bw_work_example --ttl 2h --json"],
  }),
  "work verify": commandMetadata("work verify", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work verify bw_work_example --evidence bw_evidence_example --json"],
  }),
  "work close": commandMetadata("work close", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk work close bw_work_example --reason verified --json"],
  }),
  "evidence add": commandMetadata("evidence add", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk evidence add bw_work_example --summary 'tests passed' --kind test --outcome passed --json"],
  }),
  "source add": commandMetadata("source add", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk source add --title 'Design note' --uri file://design.md --json"],
  }),
  "source list": commandMetadata("source list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "table",
    examples: ["bwrk source list --kind document --limit 20 --json"],
  }),
  "source show": commandMetadata("source show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk source show bw_source_example --json"],
  }),
  "claim create": commandMetadata("claim create", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk claim create --statement 'Search index must be fresh' --status accepted --json"],
  }),
  "claim list": commandMetadata("claim list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "table",
    examples: ["bwrk claim list --status accepted --limit 20 --json"],
  }),
  "claim show": commandMetadata("claim show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk claim show bw_claim_example --json"],
  }),
  "decision create": commandMetadata("decision create", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk decision create --title 'Use locks' --decision 'Serialize index writes' --json"],
  }),
  "decision list": commandMetadata("decision list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "table",
    examples: ["bwrk decision list --status accepted --limit 20 --json"],
  }),
  "decision show": commandMetadata("decision show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk decision show bw_decision_example --json"],
  }),
  "context rebuild": commandMetadata("context rebuild", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 150_000,
    humanOutputKind: "record",
    examples: ["bwrk context rebuild --json"],
  }),
  "context show": commandMetadata("context show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk context show bw_work_example --json"],
  }),
  "context search": commandMetadata("context search", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: true,
    concurrencySafe: true,
    requiresLock: "none",
    supportsExplain: true,
    maxResultSizeChars: 150_000,
    humanOutputKind: "table",
    examples: ["bwrk context search 'lock repair' --explain --json"],
  }),
  "search index": commandMetadata("search index", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "index",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk search index --json"],
  }),
  "search query": commandMetadata("search query", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: true,
    concurrencySafe: true,
    requiresLock: "none",
    supportsExplain: true,
    maxResultSizeChars: 150_000,
    humanOutputKind: "table",
    examples: ["bwrk search query 'reservation stale' --explain --json"],
  }),
  "reservation list": commandMetadata("reservation list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "table",
    examples: ["bwrk reservation list --agent agent-a --status active --json"],
  }),
  "agent finish": commandMetadata("agent finish", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk agent finish bw_work_example --agent agent-a --summary 'tests passed' --release --json"],
  }),
  "agent start": commandMetadata("agent start", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state+index",
    maxResultSizeChars: 150_000,
    humanOutputKind: "record",
    examples: ["bwrk agent start --agent agent-a --label hardening --purpose 'start implementation' --json"],
  }),
  "agent guide": commandMetadata("agent guide", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 50_000,
    humanOutputKind: "markdown",
    examples: ["bwrk agent guide --agent agent-a --label hardening --json"],
  }),
  "agent status": commandMetadata("agent status", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk agent status --agent agent-a --label hardening --json"],
  }),
  "session start": commandMetadata("session start", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 125_000,
    humanOutputKind: "record",
    examples: ["bwrk session start --id run-42 --agent agent-a --label hardening --json"],
  }),
  "session end": commandMetadata("session end", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 125_000,
    humanOutputKind: "record",
    examples: ["bwrk session end --session run-42 --agent agent-a --json"],
  }),
  "operation list": commandMetadata("operation list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "table",
    examples: ["bwrk operation list --session-id local --limit 20 --json"],
  }),
  "operation show": commandMetadata("operation show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk operation show bw_operation_example --json"],
  }),
  "operation prune": commandMetadata("operation prune", {
    readOnly: false,
    destructive: true,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk operation prune --keep 500 --json"],
  }),
  "operation repair": commandMetadata("operation repair", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk operation repair --json", "bwrk operation repair --dry-run --json"],
  }),
  "export json": commandMetadata("export json", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: false,
    requiresLock: "none",
    maxResultSizeChars: 1_000_000,
    humanOutputKind: "record",
    examples: ["bwrk export json --out boreal-export.json --json"],
  }),
  "export markdown": commandMetadata("export markdown", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: false,
    requiresLock: "none",
    maxResultSizeChars: 150_000,
    humanOutputKind: "record",
    examples: ["bwrk export markdown --out markdown-export --json"],
  }),
  "export ledgers": commandMetadata("export ledgers", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: false,
    requiresLock: "none",
    maxResultSizeChars: 150_000,
    humanOutputKind: "record",
    examples: ["bwrk export ledgers --json"],
  }),
  "import json": commandMetadata("import json", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk import json --from boreal-export.json --json"],
  }),
  "import ledgers": commandMetadata("import ledgers", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk import ledgers --from .boreal/ledgers --json"],
  }),
  "vault init": commandMetadata("vault init", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 125_000,
    humanOutputKind: "record",
    examples: ["bwrk vault init --json"],
  }),
  "vault status": commandMetadata("vault status", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 125_000,
    humanOutputKind: "record",
    examples: ["bwrk vault status --json"],
  }),
  "raw add": commandMetadata("raw add", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk raw add --title 'Design source' --uri file://design.md --json"],
  }),
  "wiki create": commandMetadata("wiki create", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk wiki create 'Design principles' --source bw_source_example --json"],
  }),
  "duplicate scan": commandMetadata("duplicate scan", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 150_000,
    humanOutputKind: "record",
    examples: ["bwrk duplicate scan --domain all --json"],
  }),
  "merge plan": commandMetadata("merge plan", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk merge plan --domain work --survivor bw_work_keep --duplicate bw_work_dup --json"],
  }),
  "merge apply": commandMetadata("merge apply", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk merge apply --domain work --survivor bw_work_keep --duplicate bw_work_dup --plan merge_plan_example --confirm --json"],
  }),
  "compact analyze": commandMetadata("compact analyze", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 150_000,
    humanOutputKind: "record",
    examples: ["bwrk compact analyze --older-than-days 30 --json"],
  }),
  "compact apply": commandMetadata("compact apply", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 125_000,
    humanOutputKind: "record",
    examples: ["bwrk compact apply --domain work --target bw_work_example --plan compact_plan_example --summary 'Preserved summary' --confirm --json"],
  }),
  "sync status": commandMetadata("sync status", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 125_000,
    humanOutputKind: "record",
    examples: ["bwrk sync status --json"],
  }),
  "ledger status": commandMetadata("ledger status", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk ledger status --json"],
  }),
  "ledger delete": commandMetadata("ledger delete", {
    readOnly: false,
    destructive: true,
    writesState: true,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk ledger delete source bw_source_example --reason duplicate --json"],
  }),
  "snapshot create": commandMetadata("snapshot create", {
    readOnly: false,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: false,
    requiresLock: "none",
    maxResultSizeChars: 75_000,
    humanOutputKind: "record",
    examples: ["bwrk snapshot create --name before-import --json"],
  }),
  "snapshot list": commandMetadata("snapshot list", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 100_000,
    humanOutputKind: "record",
    examples: ["bwrk snapshot list --json"],
  }),
  "snapshot show": commandMetadata("snapshot show", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 1_000_000,
    humanOutputKind: "record",
    examples: ["bwrk snapshot show snapshot-id --json"],
  }),
  doctor: commandMetadata("doctor", {
    readOnly: false,
    destructive: false,
    writesState: true,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "state+index",
    maxResultSizeChars: 250_000,
    humanOutputKind: "record",
    examples: ["bwrk doctor --json", "bwrk doctor --strict --json", "bwrk doctor --fix --json"],
  }),
  "doctor skills": commandMetadata("doctor skills", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 250_000,
    humanOutputKind: "record",
    examples: ["bwrk doctor skills --json"],
  }),
  "lock inspect": commandMetadata("lock inspect", {
    readOnly: true,
    destructive: false,
    writesState: false,
    writesGeneratedArtifacts: false,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "none",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk lock inspect --json"],
  }),
  "lock break": commandMetadata("lock break", {
    readOnly: false,
    destructive: true,
    writesState: false,
    writesGeneratedArtifacts: true,
    requiresFreshIndex: false,
    concurrencySafe: true,
    requiresLock: "recovery",
    maxResultSizeChars: 50_000,
    humanOutputKind: "record",
    examples: ["bwrk lock break --stale-only --json"],
  }),
};

const commandMatches = (command: readonly string[], definition: CommandDefinition): boolean => {
  if (command.length < definition.path.length) {
    return false;
  }
  return definition.path.every((segment, index) => command[index] === segment);
};

export const findCommandDefinition = (command: readonly string[]): CommandDefinition | undefined =>
  COMMAND_DEFINITIONS.filter((definition) => commandMatches(command, definition)).sort(
    (a, b) => b.path.length - a.path.length,
  )[0];

export const commandPath = (definition: CommandDefinition): string => definition.path.join(" ");

export function commandBehavior(definition: CommandDefinition): CommandBehaviorMetadata {
  const command = commandPath(definition);
  const behavior = COMMAND_BEHAVIOR[command];
  if (!behavior) {
    throw new BorealError("BOREAL_INVARIANT", "Command is missing behavior metadata", { command });
  }
  return behavior;
}

export function validateCommandBehaviorMetadata(): void {
  const commands = new Set(COMMAND_DEFINITIONS.map(commandPath));
  const metadataCommands = new Set(Object.keys(COMMAND_BEHAVIOR));
  const missing = [...commands].filter((command) => !metadataCommands.has(command));
  const extra = [...metadataCommands].filter((command) => !commands.has(command));
  const emptyExamples = COMMAND_DEFINITIONS.map(commandPath).filter((command) => COMMAND_BEHAVIOR[command]?.examples.length === 0);
  if (missing.length > 0 || extra.length > 0 || emptyExamples.length > 0) {
    throw new BorealError("BOREAL_INVARIANT", "Command behavior metadata is out of sync", {
      missing,
      extra,
      emptyExamples,
    });
  }
}

export function registryValueFlagNames(): ReadonlySet<string> {
  return new Set(
    [...GLOBAL_FLAGS, ...COMMAND_DEFINITIONS.flatMap((definition) => definition.flags)]
      .filter((definition) => definition.type === "value")
      .map((definition) => definition.name)
  );
}

export const serializeCommandDefinition = (definition: CommandDefinition) => ({
  path: definition.path,
  category: definition.category,
  summary: definition.summary,
  usage: definition.usage,
  description: definition.description,
  requiresWorkspace: definition.requiresWorkspace,
  supportsJson: definition.supportsJson,
  behavior: commandBehavior(definition),
  positionals: definition.positionals,
  flags: [...GLOBAL_FLAGS, ...definition.flags].map((entry) => ({
    name: entry.name,
    type: entry.type,
    repeatable: Boolean(entry.repeatable),
    summary: entry.summary,
  })),
});

export const validateCommandFlags = (args: ParsedArgs, definition: CommandDefinition): void => {
  const allowedFlags = new Map<string, FlagDefinition>();
  for (const entry of [...GLOBAL_FLAGS, ...definition.flags]) {
    allowedFlags.set(entry.name, entry);
  }

  for (const [name, values] of args.flags.entries()) {
    const definitionForFlag = allowedFlags.get(name);
    if (!definitionForFlag) {
      throw new BorealError(
        "BOREAL_INVALID_INPUT",
        `Unknown flag --${name} for bwrk ${commandPath(definition)}`,
        {
          command: definition.path,
          flag: name,
        },
      );
    }
    if (!definitionForFlag.repeatable && values.length > 1) {
      throw new BorealError(
        "BOREAL_INVALID_INPUT",
        `Flag --${name} may only be provided once for bwrk ${commandPath(definition)}`,
        {
          command: definition.path,
          flag: name,
        },
      );
    }
    if (definitionForFlag.type === "boolean") {
      const invalidValue = values.find((value) => value !== "true" && value !== "false");
      if (invalidValue) {
        throw new BorealError(
          "BOREAL_INVALID_INPUT",
          `Flag --${name} expects a boolean value for bwrk ${commandPath(definition)}`,
          {
            command: definition.path,
            flag: name,
            value: invalidValue,
          },
        );
      }
    }
  }

  const positionals = args.command.slice(definition.path.length);
  const positionalRule = definition.positionals ?? { label: "arguments", min: 0, max: 0 };
  if (positionals.length < positionalRule.min) {
    throw new BorealError(
      "BOREAL_INVALID_INPUT",
      `Missing ${positionalRule.label} for bwrk ${commandPath(definition)}`,
      {
        command: definition.path,
        expected: positionalRule,
        actual: positionals.length,
      },
    );
  }
  if (positionalRule.max !== undefined && positionals.length > positionalRule.max) {
    throw new BorealError(
      "BOREAL_INVALID_INPUT",
      `Unexpected argument for bwrk ${commandPath(definition)}`,
      {
        command: definition.path,
        expected: positionalRule,
        actual: positionals,
      },
    );
  }
};
