import { COMMAND_DEFINITIONS, GLOBAL_FLAGS, commandPath, type CommandDefinition, type FlagDefinition } from "./command-registry.js";

export type CompletionShell = "bash" | "zsh" | "fish";

export interface ShellCompletionResult {
  readonly shell: CompletionShell;
  readonly name: string;
  readonly script: string;
}

export const COMPLETION_SHELLS: readonly CompletionShell[] = ["bash", "zsh", "fish"];

export function isCompletionShell(value: string): value is CompletionShell {
  return (COMPLETION_SHELLS as readonly string[]).includes(value);
}

export function generateShellCompletion(shell: CompletionShell, name: string): ShellCompletionResult {
  const script =
    shell === "bash" ? bashCompletion(name) : shell === "zsh" ? zshCompletion(name) : fishCompletion(name);
  return { shell, name, script };
}

function bashCompletion(name: string): string {
  const functionName = `${shellIdentifier(name)}_completion`;
  return [
    `# Generated by bwrk completion bash --name ${name}`,
    "# Generated from COMMAND_DEFINITIONS; do not edit by hand.",
    commandManifestComment("#"),
    `${functionName}() {`,
    "  local cur command_key",
    "  COMPREPLY=()",
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\"",
    "  command_key=\"${COMP_WORDS[1]}\"",
    "  if [[ ${COMP_CWORD} -ge 3 && \"${COMP_WORDS[2]}\" != --* ]]; then",
    "    command_key=\"${COMP_WORDS[1]} ${COMP_WORDS[2]}\"",
    "  fi",
    "  if [[ \"${cur}\" == --* ]]; then",
    "    case \"${command_key}\" in",
    ...COMMAND_DEFINITIONS.map((definition) => {
      const command = commandPath(definition);
      return `      ${shellSingleQuote(command)}) COMPREPLY=( $(compgen -W "${flagWords(definition).join(" ")}" -- "\${cur}") ); return 0 ;;`;
    }),
    "    esac",
    "  fi",
    "  if [[ ${COMP_CWORD} -eq 1 ]]; then",
    `    COMPREPLY=( $(compgen -W "${rootCommands().join(" ")}" -- "\${cur}") )`,
    "    return 0",
    "  fi",
    "  if [[ ${COMP_CWORD} -eq 2 ]]; then",
    "    case \"${COMP_WORDS[1]}\" in",
    ...subcommandCases("bash"),
    "    esac",
    "  fi",
    "  case \"${command_key}\" in",
    ...COMMAND_DEFINITIONS.map((definition) => {
      const command = commandPath(definition);
      return `    ${shellSingleQuote(command)}) COMPREPLY=( $(compgen -W "${flagWords(definition).join(" ")}" -- "\${cur}") ); return 0 ;;`;
    }),
    "  esac",
    "}",
    `complete -F ${functionName} ${name}`,
    ""
  ].join("\n");
}

function zshCompletion(name: string): string {
  const functionName = `_${shellIdentifier(name)}_completion`;
  return [
    `#compdef ${name}`,
    `# Generated by bwrk completion zsh --name ${name}`,
    "# Generated from COMMAND_DEFINITIONS; do not edit by hand.",
    commandManifestComment("#"),
    `${functionName}() {`,
    "  local cur command_key",
    "  cur=\"${words[CURRENT]}\"",
    "  command_key=\"${words[2]}\"",
    "  if (( CURRENT >= 4 )) && [[ \"${words[3]}\" != --* ]]; then",
    "    command_key=\"${words[2]} ${words[3]}\"",
    "  fi",
    "  if [[ \"${cur}\" == --* ]]; then",
    "    case \"${command_key}\" in",
    ...COMMAND_DEFINITIONS.map((definition) => {
      const command = commandPath(definition);
      return `      ${shellSingleQuote(command)}) compadd -- ${zshWords(flagWords(definition))}; return 0 ;;`;
    }),
    "    esac",
    "  fi",
    "  if (( CURRENT == 2 )); then",
    `    compadd -- ${zshWords(rootCommands())}`,
    "    return 0",
    "  fi",
    "  if (( CURRENT == 3 )); then",
    "    case \"${words[2]}\" in",
    ...subcommandCases("zsh"),
    "    esac",
    "  fi",
    "  case \"${command_key}\" in",
    ...COMMAND_DEFINITIONS.map((definition) => {
      const command = commandPath(definition);
      return `    ${shellSingleQuote(command)}) compadd -- ${zshWords(flagWords(definition))}; return 0 ;;`;
    }),
    "  esac",
    "}",
    `${functionName} "$@"`,
    ""
  ].join("\n");
}

function fishCompletion(name: string): string {
  const lines = [
    `# Generated by bwrk completion fish --name ${name}`,
    "# Generated from COMMAND_DEFINITIONS; do not edit by hand.",
    commandManifestComment("#"),
    `complete -c ${fishToken(name)} -f`
  ];

  for (const flag of GLOBAL_FLAGS) {
    lines.push(fishFlagLine(name, undefined, flag));
  }
  for (const command of rootCommands()) {
    const definition = COMMAND_DEFINITIONS.find((candidate) => candidate.path[0] === command);
    lines.push(
      `complete -c ${fishToken(name)} -n "__fish_use_subcommand" -a ${fishToken(command)} -d ${fishToken(
        definition?.summary ?? command
      )}`
    );
  }
  for (const [root, subcommands] of subcommandsByRoot()) {
    for (const subcommand of subcommands) {
      const definition = COMMAND_DEFINITIONS.find(
        (candidate) => candidate.path[0] === root && candidate.path[1] === subcommand
      );
      lines.push(
        `complete -c ${fishToken(name)} -n "__fish_seen_subcommand_from ${fishToken(root)}" -a ${fishToken(
          subcommand
        )} -d ${fishToken(definition?.summary ?? subcommand)}`
      );
    }
  }
  for (const shell of COMPLETION_SHELLS) {
    lines.push(
      `complete -c ${fishToken(name)} -n "__fish_seen_subcommand_from completion" -a ${fishToken(shell)} -d ${fishToken(
        `${shell} completion script`
      )}`
    );
  }
  for (const definition of COMMAND_DEFINITIONS) {
    for (const flag of definition.flags) {
      lines.push(fishFlagLine(name, fishCondition(definition.path), flag));
    }
  }
  lines.push("");
  return lines.join("\n");
}

function rootCommands(): readonly string[] {
  return unique(COMMAND_DEFINITIONS.map((definition) => definition.path[0]).filter(isString));
}

function subcommandsByRoot(): ReadonlyMap<string, readonly string[]> {
  const entries = new Map<string, string[]>();
  for (const definition of COMMAND_DEFINITIONS) {
    if (definition.path.length < 2) {
      continue;
    }
    const root = definition.path[0];
    const subcommand = definition.path[1];
    if (!root || !subcommand) {
      continue;
    }
    entries.set(root, unique([...(entries.get(root) ?? []), subcommand]) as string[]);
  }
  entries.set("completion", [...COMPLETION_SHELLS]);
  return entries;
}

function flagWords(definition: CommandDefinition): readonly string[] {
  return unique([...GLOBAL_FLAGS, ...definition.flags].map((flag) => `--${flag.name}`));
}

function subcommandCases(shell: "bash" | "zsh"): readonly string[] {
  return [...subcommandsByRoot()].map(([root, subcommands]) => {
    if (shell === "bash") {
      return `      ${shellSingleQuote(root)}) COMPREPLY=( $(compgen -W "${subcommands.join(" ")}" -- "\${cur}") ); return 0 ;;`;
    }
    return `      ${shellSingleQuote(root)}) compadd -- ${zshWords(subcommands)}; return 0 ;;`;
  });
}

function commandManifestComment(prefix: string): string {
  return `${prefix} Commands: ${COMMAND_DEFINITIONS.map(commandPath).join(", ")}`;
}

function fishFlagLine(name: string, condition: string | undefined, flag: FlagDefinition): string {
  const requiresValue = flag.type === "value" ? " -r" : "";
  const conditionPart = condition ? ` -n ${fishToken(condition)}` : "";
  return `complete -c ${fishToken(name)}${conditionPart} -l ${fishToken(flag.name)}${requiresValue} -d ${fishToken(flag.summary)}`;
}

function fishCondition(path: readonly string[]): string {
  return path.map((part) => `__fish_seen_subcommand_from ${fishToken(part)}`).join("; and ");
}

function shellIdentifier(value: string): string {
  return value.replace(/[^A-Za-z0-9_]/g, "_");
}

function zshWords(values: readonly string[]): string {
  return values.map(shellSingleQuote).join(" ");
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function fishToken(value: string): string {
  return shellSingleQuote(value);
}

function unique(values: readonly string[]): readonly string[] {
  return [...new Set(values)];
}

function isString(value: string | undefined): value is string {
  return typeof value === "string";
}
