export const BWRK_DELEGATION_GUARD_ENV = "BOREAL_BWRK_DELEGATED";
export const BWRK_LAUNCHER_NAME_ENV = "BOREAL_BWRK_LAUNCHER_NAME";
export const BWRK_LAUNCHER_VERSION_ENV = "BOREAL_BWRK_LAUNCHER_VERSION";
export const BWRK_LAUNCHER_CHANNEL_ENV = "BOREAL_BWRK_LAUNCHER_CHANNEL";
export const BWRK_LAUNCHER_EXECUTABLE_ENV = "BOREAL_BWRK_LAUNCHER_EXECUTABLE";
export const BWRK_DELEGATED_BIN_ENV = "BOREAL_BWRK_DELEGATED_BIN";
