import type { Item, Note, Project, Status, Association, LinkedProject } from "./client.js";
import { GlobalController, isDone, isOverdue, type Row, type Route } from "./model.js";
import { clip, fit, wrapWords } from "./terminal/cells.js";

export const ROUTE_MENU: Array<[Route,string]> = [["overview","Home"],["projects","Projects"],["board","Board"],["list","List"],["todos","Today / open"],["notes","Notes"],["workflow","Workflow"],["links","Linked"],["planning","Plan"],["archive","Archive"],["history","History"],["inbox","Inbox"]];
const routes=ROUTE_MENU;
export function render(c:GlobalController,width=100,height=40):string {
  width=Math.max(20,Math.floor(width));height=Math.max(8,Math.floor(height));
  const snap=c.snapshot;if(!snap){const state=c.refreshing?"Connecting to the global manager…":c.lastRefreshError?`Global manager unavailable · ${c.lastRefreshError}`:"Global manager has not loaded a snapshot yet.";return [fit("BOREAL  Global management",width),fit(state,width),fit("Press r to retry the read · q to quit",width),"─".repeat(width)].slice(0,height).map(line=>fit(line,width)).join("\n");}
  const wide=width>=112, medium=width>=76;
  const inspectorOnly=!wide&&c.focus==="inspector";
  const navigationOnly=!medium&&c.focus==="navigation";
  const navWidth=medium&&!inspectorOnly?19:0, inspectorWidth=wide?30:inspectorOnly?width:0;
  const workWidth=inspectorOnly?0:Math.max(18,width-navWidth-inspectorWidth-(navWidth?3:0)-(inspectorWidth?3:0));
  const head=header(c,width,height<=24);
  const bodyHeight=Math.max(1,height-head.length-1);
  const nav=navWidth?navigation(c,navWidth,bodyHeight):[];
  const inspector=inspectorWidth?inspect(c,inspectorWidth,bodyHeight):[];
  let work:string[];
  if(inspectorOnly)work=[];
  else if(navigationOnly)work=navigation(c,width,bodyHeight);
  else if(c.route==="board")work=board(c,workWidth,bodyHeight);
  else if(c.route==="overview")work=overview(c,workWidth,bodyHeight);
  else if(c.route==="planning")work=planning(c,workWidth,bodyHeight);
  else if(c.route==="history")work=history(c,workWidth,bodyHeight);
  else work=list(c,workWidth,bodyHeight);
  const body:string[]=[];
  for(let i=0;i<bodyHeight;i++){
    const left=navWidth?fit(nav[i]??"",navWidth):"";
    const center=fit(work[i]??"",workWidth);
    const right=inspectorWidth?fit(inspector[i]??"",inspectorWidth):"";
    body.push(inspectorOnly?right:navWidth?`${left} │ ${center}${inspectorWidth?` │ ${right}`:""}`:center);
  }
  return [...head,...body].slice(0,height).map(line=>fit(line,width)).join("\n");
}
function header(c:GlobalController,width:number,compact=false):string[]{
 const p=c.snapshot?.projects.find(x=>x.id===c.projectId);const snap=c.snapshot!;const open=snap.items.filter(i=>!i.archived&&!(i.project_id&&snap.projects.some(p=>p.id===i.project_id&&p.archived))&&!isDone(c.statusFor(i)));const scopedOpen=open.filter(i=>!c.projectId||i.project_id===c.projectId);const overdue=scopedOpen.filter(i=>isOverdue(i));const attention=c.projectId?snap.attention?.projects[c.projectId]:snap.attention?.portfolio;
 const sampled=c.sampledAt?`${Math.max(0,Math.floor((Date.now()-c.sampledAt)/1000))}s ago`:"not sampled";
 const freshness=c.refreshing?"refreshing…":c.lastRefreshError?`stale · ${c.lastRefreshError}`:`fresh · ${sampled}`;
 const scope=c.projectId?`Project: ${p?.name??"unknown"}`:c.route==="inbox"?"Personal inbox + all project inboxes":"All projects";const totalLabel=attention?`${attention.open} open · ${attention.overdue} overdue · ${attention.waiting} waiting · ${attention.unscheduled} unscheduled · ${attention.due_today} due today`:`visible sample ${scopedOpen.length} open · ${overdue.length} overdue`;
 const title=fit(`BOREAL  ${p?clip(p.name,width-20):c.route==="inbox"?"Personal inbox":"Portfolio"}  /  ${label(c.route)}${c.route==="todos"?` · ${c.todoFilter.replace("_"," ")}`:""}`,width);
 const context=fit(`${scope} · rev ${snap.revision} · ${compact?freshness:`${totalLabel} · ${c.projects.length} projects · ${freshness}`}`,width);
 const recovery=fit(`${c.notice||"↑↓ move · PgDn more · Enter inspect · ? help"}${c.searchQuery?` · Filter: ${c.searchQuery}`:""}${c.unresolvedOperation?`  ·  WRITE FROZEN: ${c.unresolvedOperation}`:""}`,width);
 return compact?[title,context,recovery]:[title,context,recovery,"─".repeat(width)];
}
function navigation(c:GlobalController,w:number,h:number):string[]{const groups:[string,Array<[Route,string]>][]=[["GLOBAL",routes.filter(([r])=>["overview","inbox","todos","projects"].includes(r))],["CURRENT PROJECT",routes.filter(([r])=>["board","list","planning","notes","workflow"].includes(r))],["PROJECT CONTEXT",routes.filter(([r])=>r==="links")],["SECONDARY",routes.filter(([r])=>["archive","history"].includes(r))]];const menu:string[]=[];for(const [heading,entries] of groups){menu.push(heading);for(const [route,name] of entries)menu.push(`${c.route===route?(c.focus==="navigation"?"▸":"›"):" "} ${name}`);}menu.push("","PROJECT SCOPE",...(c.projectId?[`› ${c.activeProject?.name??"Archived project"}`,"  Space · change scope"]:["› All projects",...c.projects.map(p=>`  ${p.name}`)]));const active=menu.findIndex(x=>x.endsWith(` ${label(c.route)}`));const start=Math.max(0,Math.min(menu.length-Math.max(1,h),active-Math.floor(h/2)));const page=menu.slice(start,start+Math.max(1,h));if(start>0&&page.length)page[0]="↑ Views and scope";if(start+page.length<menu.length&&page.length)page[page.length-1]="↓ More views";return page.map(x=>clip(x,w));}
function list(c:GlobalController,w:number,h:number):string[]{const rows=c.rows();const collection=({projects:"projects",board:"items",list:"items",todos:"items",inbox:"items",notes:"notes",workflow:"statuses",links:"associations",planning:"items"} as Record<string,string>)[c.route];const exact=c.pageTotals.get(`${c.route}:${c.projectId??"*"}:${c.searchQuery}:${collection}`);const storeTotal=!c.projectId&&!c.searchQuery&&collection?c.snapshot?.totals?.[collection]:undefined;const total=exact??storeTotal;const title=`${label(c.route)}  ${rows.length}${total===undefined?" loaded":` shown · ${total} total`}${total!==undefined&&rows.length<total?" · PgDn more":""}${c.pageLoading?" · loading":""}${c.searchQuery?`  ·  “${c.searchQuery}”`:""}`;const lines=[title,"─".repeat(w)];const rendered=rows.flatMap((row,i)=>rowLines(c,row,i===c.selected,w));const sel=c.route==="board"?c.rowKey(c.boardSelected):c.selectedId;let ix=rendered.findIndex(line=>line.startsWith(`@${sel}@`));if(ix<0)ix=0;const avail=Math.max(1,h-lines.length);const start=Math.max(0,Math.min(rendered.length-avail,ix-Math.floor(avail/2)));lines.push(...rendered.slice(start,start+avail));return lines.map(x=>clip(x.replace(/^@[^@]*@/,""),w));}
function rowLines(c:GlobalController,row:Row,selected:boolean,w:number):string[]{const mark=selected?(c.focus==="work"?"▸":"›"):" ";
 const key=c.rowKey(row)??"";
 if("operation_id" in row){const origin=!c.projectId&&row.project_id?` · ${c.projectName(row.project_id)}`:"";return [`@${key}@${mark} r${row.revision} · ${formatDate(row.created_at)}${origin} · ${row.title??row.command}`,`@${key}@   ${row.summary}`];}
 if("name" in row)return [`@${key}@${mark} ◇ ${row.name}`,`@${key}@   ${row.lifecycle??"active"} · ${row.health??"health unknown"}${row.description?` · ${row.description}`:""}`];
 if("title" in row && "status_id" in row){const i=row as Item;const status=c.statusFor(i);const overdue=isOverdue(i)&&!isDone(status);const origin=!c.projectId?` · ${c.projectName(i.project_id)}`:"";const follow=(i as Item&{follow_up_at?:string|null}).follow_up_at;const waiting=status?.category==="waiting"||status?.status_id.toLowerCase()==="waiting";const attention=waiting?`WAITING${follow?` · follow up ${formatDate(follow)}`:""}`:overdue?"OVERDUE":!i.due_at?"UNSCHEDULED":isToday(i.due_at)?"DUE TODAY":"";const bulk=c.bulkSelectedIds.has(i.id)?"☑ ":"";return [`@${key}@${mark} ${bulk}${status?.label??i.status_id}${attention?` · ${attention}`:""}${origin}${i.priority===null?"":` · P${i.priority}`}  ${i.title}`,...(i.description?wrapWords(`   ${i.description}`,Math.max(10,w)).map(x=>`@${key}@${x}`):[]),...(i.parent_id?[`@${key}@   ↳ parent ${parentTitle(c,i.parent_id)}`]:[])];}
 if("title" in row){const n=row as Note;const origin=!c.projectId?` · ${c.projectName(n.project_id)}`:"";return [`@${key}@${mark} ▤ ${n.title}${origin}`,...wrapWords(n.body,Math.max(10,w-3)).slice(0,3).map(x=>`@${key}@   ${x}`)];}
 if("position" in row && "status_id" in row){const s=row as Status;const origin=!c.projectId?`${c.projectName(s.project_id)} · `:"";return [`@${key}@${mark} ${origin}${s.position+1}. ${s.label} · ${s.category}`];}
 const a=row as Association;const roll=linked(c,a);const origin=!c.projectId?` · ${c.projectName(a.project_id)}`:"";return [`@${key}@${mark} ${a.kind} · ${a.identity}${origin}`,...(roll?[`@${key}@   ${roll.counts?`${Object.entries(roll.counts).map(([k,v])=>`${k} ${v}`).join(" / ")} · `:""}${roll.availability} · rev ${roll.revision??"?"} · as of ${roll.as_of?formatDate(roll.as_of):"time unavailable"}`,`@${key}@   ${a.path??"No folder path"}`,...(roll.items??[]).slice(0,6).map(item=>`@${key}@     ${item.display_status} · ${item.title}`)]:[`@${key}@   ${a.path??"No folder path"}`])];}
function board(c:GlobalController,w:number,h:number):string[]{const statuses=c.boardStatuses;if(!statuses.length){const links=c.projectId?c.snapshot!.associations.filter(a=>a.project_id===c.projectId&&a.kind==="workspace"):[];return ["Board", "", "No personal items in this scope.",...links.map(a=>{const roll=linked(c,a);return rollupShort(c,a);})];}
 const colsFit=Math.max(1,Math.floor(w/22));const count=Math.min(statuses.length,colsFit);let start=Math.max(0,Math.min(statuses.length-count,c.boardColumn-Math.floor(count/2)));if(c.boardColumn<start)start=c.boardColumn;
 const shown=statuses.slice(start,start+count);const cw=Math.floor(w/count);const out=[`${c.projectId?c.activeProject?.name:"All projects"} · board  [${c.boardColumn+1}/${statuses.length}]`,"─".repeat(w)];
 const cards=shown.map(s=>c.items.filter(i=>i.project_id===s.project_id&&i.status_id===s.status_id));const links=c.projectId?c.snapshot!.associations.filter(a=>a.project_id===c.projectId&&a.kind==="workspace"):[];const rows=Math.max(0,h-out.length-links.length);const cardLines=Math.max(0,rows-1);
 const starts=cards.map((list,index)=>{if(start+index!==c.boardColumn)return 0;return Math.max(0,Math.min(list.length-cardLines,c.boardCard-Math.floor(cardLines/2)));});
 for(let y=0;y<rows;y++){
   const cells=shown.map((s,index)=>{const list=cards[index];if(y===0)return clip(`${s.project_id!==c.projectId?`${projectName(c,s.project_id)} · `:""}${s.label} (${list.length}${c.snapshot?.snapshot_limit&&c.snapshot.items.length>=c.snapshot.snapshot_limit?"+":""})`,cw-1);const item=list[starts[index]+y-1];if(!item)return "";const selected=item.id===c.boardSelected?.id;return clip(`${selected?(c.focus==="work"?"▸":"›"):" "} ${c.bulkSelectedIds.has(item.id)?"☑ ":""}${item.kind==="subtask"?"↳ ":""}${item.title}`,cw-2);});out.push(cells.map(x=>fit(x,cw)).join(" ").slice(0,w));}
 if(statuses.length>count)out[0]=`${out[0]} · ←/→ columns`;
 for(const a of links)out.push(rollupShort(c,a));
 return out;}
function overview(c:GlobalController,w:number,h:number):string[]{const rows=c.rows();const a=c.snapshot?.attention;const counts=c.projectId?a?.projects[c.projectId]:a?.portfolio;const summary=counts?`ATTENTION · ${counts.overdue} overdue · ${counts.waiting} waiting · ${counts.due_today} due today · ${counts.unscheduled} unscheduled`:"Attention groups reflect the loaded snapshot";const out=[`Home · ${rows.length} actionable records and project summaries`,summary,"─".repeat(w)];const rendered=rows.flatMap((r,i)=>{
 if("status_id" in r&&"title" in r){const item=r as Item;const status=c.statusFor(item);const follow=(item as Item&{follow_up_at?:string|null}).follow_up_at;const group=status?.category==="waiting"||status?.status_id.toLowerCase()==="waiting"?`WAITING${follow?` · follow up ${formatDate(follow)}`:""}`:isOverdue(item)?"OVERDUE OBLIGATIONS":!item.due_at?"UNSCHEDULED":"OPEN WORK";const marked=i===c.selected?(c.focus==="work"?"▸":"›"):" ";return [`@${item.id}@${marked} ${group} · ${item.title} · ${c.projectName(item.project_id)} · ${status?.label??item.status_id}${item.priority===null?"":` · P${item.priority}`}`];}
 if("name" in r){const p=r as Project;const next=c.projectNextAction(p),milestone=c.projectNextMilestone(p),activity=c.projectLastActivity(p);const visibleCount=c.snapshot!.items.filter(i=>i.project_id===p.id&&!i.archived&&!isDone(c.statusFor(i))).length;const count=c.snapshot?.attention?.projects[p.id]?.open;const links=c.snapshot!.associations.filter(a=>a.project_id===p.id&&a.kind==="workspace");const linkedCount=links.length;const unavailable=links.filter(a=>{const sample=c.snapshot!.linked_projects?.find(x=>x.management_project_id===p.id&&x.project_id===a.identity);return !sample||sample.availability!=="available";}).length;const prefix=i===c.selected?(c.focus==="work"?"▸":"›"):" ";const milestoneProgress=milestone?("completed_children" in milestone?` · ${milestone.completed_children}/${milestone.total_children} children complete`:(()=>{const item=c.snapshot!.items.find(x=>x.id===milestone.id);if(!item)return " · progress unavailable";const progress=c.milestoneProgress(item);return ` · ${progress.completed}/${progress.total} completed of visible children`;})()):"";return [`@${p.id}@${prefix} PROJECT ${p.name} · ${p.lifecycle??"active"} · health ${p.health??"unknown"} · ${count??`${visibleCount} visible`} management open`, `@${p.id}@   Next action: ${next?.title??"none"}${next?.due_at?` · due ${formatDate(next.due_at)}`:""}`,`@${p.id}@   Next milestone: ${milestone?.title??"none"}${milestone?.due_at?` · ${formatDate(milestone.due_at)}`:""}${milestoneProgress}`,`@${p.id}@   Last management activity: ${activity?`${activity.summary} · ${formatDate(activity.created_at)}`:"not in recent activity sample"}`,`@${p.id}@   ${linkedCount} linked execution workspace${linkedCount===1?"":"s"} · ${unavailable?`${unavailable} unavailable · `:""}progress shown separately in Linked`];}
 return rowLines(c,r,i===c.selected,w);
 });let ix=rendered.findIndex(line=>line.startsWith(`@${c.selectedId}@`));if(ix<0)ix=0;const cap=Math.max(1,h-out.length);const start=Math.max(0,Math.min(rendered.length-cap,ix-Math.floor(cap/2)));out.push(...rendered.slice(start,start+cap).map(x=>clip(x.replace(/^@[^@]*@/,""),w)));return out;}
function planning(c:GlobalController,w:number,h:number):string[]{const items=c.rows().filter((r):r is Item=>"title" in r&&"status_id" in r);const out=[`Planning hierarchy · ${items.length} visible items · z collapse · y/Y bulk select`,"─".repeat(w)];const selected=items.findIndex(i=>i.id===c.selectedId);const cap=Math.max(0,h-out.length);const start=Math.max(0,Math.min(items.length-cap,selected<0?0:selected-Math.floor(cap/2)));for(const item of items.slice(start,start+cap)){const depth=c.itemBreadcrumb(item).length;const collapsed=c.isCollapsed(item.id);const progress=item.kind==="milestone"?c.milestoneProgress(item):undefined;const marker=item.id===c.selectedId?(c.focus==="work"?"▸":"›"):" ";const bulk=c.bulkSelectedIds.has(item.id)?"☑":"☐";const ancestry=c.itemBreadcrumb(item);const breadcrumb=ancestry.length?`  [${ancestry.join(" / ")}]`:"";const counts=progress?` · ${progress.completed}/${progress.total} ${progress.visibleOnly?"visible children":"children complete"}`:"";out.push(`${marker}${bulk} ${"  ".repeat(Math.min(depth,8))}${item.parent_id?(collapsed?"▸":"▾"):" "} ${item.kind==="milestone"?"◆":item.kind==="subtask"?"↳":"•"} ${item.title}  · ${c.statusFor(item)?.label??item.status_id}${counts}${breadcrumb}`);}return out;}
function history(c:GlobalController,w:number,h:number):string[]{const records=c.rows().filter((r):r is import("./model.js").ActivityRow=>"operation_id" in r);const out=[`Activity timeline · ${c.historyTotal||records.length} events · revision ${c.snapshot?.revision??"?"}`,"─".repeat(w)];const selected=records.findIndex(e=>c.rowKey(e)===c.selectedId);const cap=Math.max(0,h-out.length);const start=Math.max(0,Math.min(records.length-cap,selected<0?0:selected-Math.floor(cap/2)));for(const e of records.slice(start,start+cap)){out.push(`${c.rowKey(e)===c.selectedId?"›":" "} r${e.revision} · ${formatDate(e.created_at)} · ${e.title??e.command}`,`   ${e.summary}`);}if(!records.length)out.push(c.historyError?`Activity unavailable · ${c.historyError}`:"No activity events are available.");if(c.historyHasMore)out.push("More history available; page down to load more.");return out;}
function inspect(c:GlobalController,w:number,h:number):string[]{const r=c.selectedRow();const tabs:[GlobalController["inspectorTab"],string][]=[["details","Details"],["relationships","Links"],["history","History"],["linked","Execution"]];const out=[`INSPECT · ${c.focus==="inspector"?"focused":""}`,tabs.map(([id,name])=>id===c.inspectorTab?`[${name}]`:name).join("  "),"─".repeat(w)];const content:string[]=[];if(!r)content.push("Select a record to inspect.");
 else if("operation_id" in r)content.push(r.title??r.command,`Revision ${r.revision} · ${formatDate(r.created_at)}`,r.summary,`Operation ${r.operation_id}`);
 else if("title" in r&&"status_id" in r){const i=r as Item;
   if(c.inspectorTab==="details")content.push(i.title,`Status: ${c.statusFor(i)?.label??i.status_id}`,`Project: ${projectName(c,i.project_id)}`,`Kind: ${i.kind} · ${i.id}`,`Priority: ${i.priority??"none"}`,`Due: ${i.due_at?formatDate(i.due_at):"none"}`,`Parent: ${i.parent_id?parentTitle(c,i.parent_id):"none"}`,`Path: ${c.itemBreadcrumb(i).join(" / ")||"top level"}`,...(i.parent_id?[`Hierarchy: ${[...c.itemBreadcrumb(i),i.title].join(" › ")}`]:[]),...(Array.isArray(i.linked_notes)?[`Linked notes (${i.linked_notes.length})`,...(i.linked_notes.length?i.linked_notes.map(note=>note.title):["No linked notes."])]:[]),...(i.kind==="milestone"?[`Progress: ${(()=>{const p=c.milestoneProgress(i);return `${p.completed}/${p.total} ${p.visibleOnly?"visible children":"children complete"}`;})()}`]:[]),"",...wrapWords(i.description||"No description.",w));
   if(c.inspectorTab==="relationships"){const rel=c.relationshipsFor(i);content.push(i.title,"Relationships and dependencies");if(!rel.length)content.push("No relationships recorded.");for(const x of rel){const relatedId=x.source_id===i.id?x.target_id:x.source_id;const related=relatedTitle(c,relatedId);const direction=x.kind==="depends_on"?(x.source_id===i.id?`Waiting on ${related}`:`Blocks ${related}`):x.kind==="blocks"?(x.source_id===i.id?`Blocks ${related}`:`Waiting on ${related}`):`${x.kind} · ${related}`;content.push(`${direction} [${relatedId}]`);}}
   if(c.inspectorTab==="history"){const events=c.statusHistoryFor(i);content.push(i.title,"Status changes");for(const e of events)content.push(`r${e.revision} · ${formatDate(e.changed_at)} · ${e.from_status_id??"created"} → ${e.to_status_id}`);for(const e of c.historyEvents.filter(e=>e.entity_id===i.id))content.push(`r${e.revision} · ${formatDate(e.created_at)} · ${e.summary}`);if(!events.length&&!c.historyEvents.some(e=>e.entity_id===i.id))content.push("No retained activity for this item.");}
   if(c.inspectorTab==="linked"){content.push(i.title,`Management project: ${projectName(c,i.project_id)}`);const associations=c.snapshot!.associations.filter(a=>a.project_id===i.project_id&&a.kind==="workspace");if(!associations.length)content.push("No linked execution workspaces.");for(const a of associations){const roll=linked(c,a);content.push(a.identity,a.path??"path unavailable",roll?`${roll.availability} · revision ${roll.revision??"?"} · sampled ${formatDate(roll.as_of??"")}${roll.counts?` · ${Object.entries(roll.counts).map(([k,v])=>`${k} ${v}`).join(" / ")}`:""}`:"Execution progress unavailable",...(roll?.items??[]).slice(0,8).map(x=>`${x.display_status} · ${x.title}`),...(roll?.items_has_more?[linkedPageHint(roll)]:[]));}}
 }
 else if("name" in r){const p=r as Project;
   if(c.inspectorTab==="details")content.push(p.name,p.description||"No description.",`Lifecycle: ${p.lifecycle??"active"}`,`Health: ${p.health??"unknown"}`,`Items: ${c.snapshot!.items.filter(i=>i.project_id===p.id&&!i.archived).length}`);
   if(c.inspectorTab==="relationships")for(const a of c.snapshot!.associations.filter(a=>a.project_id===p.id)){const roll=linked(c,a);content.push(`${a.kind} · ${a.identity}`,roll?`${roll.availability} · revision ${roll.revision??"?"} · ${formatDate(roll.as_of??"")}${roll.counts?` · ${Object.entries(roll.counts).map(([k,v])=>`${k} ${v}`).join(" / ")}`:""}`:"Progress unavailable");}
   if(c.inspectorTab==="history")content.push(...c.historyEvents.filter(e=>e.entity_id===p.id).map(e=>`r${e.revision} · ${formatDate(e.created_at)} · ${e.summary}`));
   if(c.inspectorTab==="linked")for(const a of c.snapshot!.associations.filter(a=>a.project_id===p.id&&a.kind==="workspace")){const roll=linked(c,a);content.push(a.identity,a.path??"path unavailable",roll?`${roll.availability} · rev ${roll.revision??"?"} · sampled ${formatDate(roll.as_of??"")}`:"Progress unavailable",...(roll?.items??[]).slice(0,8).map(x=>`${x.display_status} · ${x.title}`));}if(!content.length)content.push("No linked workspaces.");
 }
 else if("title" in r){const n=r as Note;if(c.inspectorTab==="details")content.push(n.title,`Updated ${formatDate(n.updated_at)}`,...(Array.isArray(n.linked_items)?["",`Linked work (${n.linked_items.length})`,...(n.linked_items.length?n.linked_items.map(item=>item.title):["No linked work items."])]:[]),"",...wrapWords(n.body,w));else if(c.inspectorTab==="history")content.push(...c.historyEvents.filter(e=>e.entity_id===n.id).map(e=>`r${e.revision} · ${formatDate(e.created_at)} · ${e.summary}`));else content.push("No additional information for this note.");}
 else if("position" in r&&"status_id" in r)content.push(r.label,`Category: ${r.category}`,`Position: ${r.position+1}`,`Status ID: ${r.status_id}`);
 else {const a=r as Association;const roll=linked(c,a);content.push(a.kind,a.identity,a.path??"path unavailable",roll?`${roll.availability} · source revision ${roll.revision??"?"} · sampled ${formatDate(roll.as_of??"")}`:"Progress unavailable",...(roll?.counts?[Object.entries(roll.counts).map(([k,v])=>`${k}: ${v}`).join(" · ")]:[]),...(roll?.items??[]).slice(0,10).map(item=>`${item.display_status} · ${item.title}`),...(roll?.items_has_more?[linkedPageHint(roll)]:[]));}
 const contentHeight=Math.max(0,h-out.length);const wrapped=content.flatMap(line=>wrapWords(line,w));return [...out,...wrapped.slice(c.inspectorOffset,c.inspectorOffset+contentHeight)].map(x=>clip(x,w));}
function label(route:Route):string{return routes.find(x=>x[0]===route)?.[1]??route;}
function updated(r:Row):string{return "updated_at" in r?r.updated_at:"";}
function formatDate(value:string):string{if(!value)return "time unavailable";if(/^\d{4}-\d{2}-\d{2}$/u.test(value))return value;const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"});}
function isToday(value:string):boolean{if(/^\d{4}-\d{2}-\d{2}$/u.test(value))return value===new Date().toISOString().slice(0,10);const d=new Date(value);return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===new Date().toISOString().slice(0,10);}
function parentTitle(c:GlobalController,id:string):string{return c.snapshot?.items.find(i=>i.id===id)?.title??id;}
function relatedTitle(c:GlobalController,id:string):string{return parentTitle(c,id);}
function projectName(c:GlobalController,id:string|null):string{return c.snapshot?.projects.find(p=>p.id===id)?.name??(id?"Unknown project":"Personal");}
function linked(c:GlobalController,a:Association):LinkedProject|undefined{return c.snapshot?.linked_projects?.find(x=>x.management_project_id===a.project_id&&x.project_id===a.identity&&(!a.path||x.path===a.path));}
function linkedPageHint(sample:LinkedProject):string{return `Showing ${sample.items?.length??0} of ${sample.items_total??"?"} linked work items · PgDn loads more`;}
function rollupShort(c:GlobalController,a:Association):string{const r=linked(c,a);return `${a.identity}${r?.counts?` · ${Object.entries(r.counts).map(([k,v])=>`${k} ${v}`).join(" / ")}`:""} · ${r?.availability??"progress unavailable"}${r?.revision==null?"":` · rev ${r.revision}`}`;}
